export const fruitsData = [
  {
    src: '/_nuxt/public/img/form7.png',
    audioSrc: '/_nuxt/public/audio/fruits/7_l.mp3',
    color: '#2de43f',
    index: 0,
    score: 10,
    point: 6,
  },
  {
    src: '/_nuxt/public/img/form5.png',
    audioSrc: '/_nuxt/public/audio/fruits/5_l.mp3',
    color: '#f038c4',
    index: 1,
    score: 20,
    point: 4,
  },
  {
    src: '/_nuxt/public/img/form1.png',
    audioSrc: '/_nuxt/public/audio/fruits/1_l.mp3',
    color: '#fd9a38',
    index: 2,
    score: 120,
    point: 0,
  },
  {
    src: '/_nuxt/public/img/form1-2.png',
    audioSrc: '/_nuxt/public/audio/fruits/1_s.mp3',
    color: '#2de43f',
    index: 3,
    score: 50,
    point: 0,
  },
  {
    src: '/_nuxt/public/img/form8.png',
    audioSrc: '/_nuxt/public/audio/fruits/8_l.mp3',
    color: '#f038c4',
    index: 4,
    score: 5,
    point: 7,
  },
  {
    src: '/_nuxt/public/img/form8-2.png',
    audioSrc: '/_nuxt/public/audio/fruits/8_s.mp3',
    color: '#fd9a38',
    index: 5,
    score: 2,
    point: 7,
  },
  {
    src: '/_nuxt/public/img/form6.png',
    audioSrc: '/_nuxt/public/audio/fruits/6_l.mp3',
    color: '#2de43f',
    index: 6,
    score: 15,
    point: 5,
  },
  {
    src: '/_nuxt/public/img/form5-2.png',
    audioSrc: '/_nuxt/public/audio/fruits/5_s.mp3',
    color: '#f038c4',
    index: 23,
    score: 2,
    point: 4,
  },
  {},
  {},
  {},
  {},
  {},
  {
    src: '/_nuxt/public/img/form4.png',
    audioSrc: '/_nuxt/public/audio/fruits/4_l.mp3',
    color: '#f038c4',
    index: 7,
    score: 20,
    point: 3,
  },
  {
    src: '/_nuxt/public/img/form8.png',
    audioSrc: '/_nuxt/public/audio/fruits/8_l.mp3',
    color: '#fd9a38',
    index: 22,
    score: 5,
    point: 7,
  },
  {},
  {},
  {},
  {},
  {},
  {
    src: '/_nuxt/public/img/form4-2.png',
    audioSrc: '/_nuxt/public/audio/fruits/4_s.mp3',
    color: '#fd9a38',
    index: 8,
    score: 2,
    point: 3,
  },
  {
    src: '/_nuxt/public/img/forms.png',
    color: '#dd1f1f',
    index: 21,
  },
  {},
  {},
  {},
  {},
  {},
  {
    src: '/_nuxt/public/img/forms.png',
    color: '#dd1f1f',
    index: 9,
  },
  {
    src: '/_nuxt/public/img/form3-2.png',
    audioSrc: '/_nuxt/public/audio/fruits/3_s.mp3',
    color: '#2de43f',
    index: 20,
    score: 2,
    point: 2,
  },
  {},
  {},
  {},
  {},
  {},
  {
    src: '/_nuxt/public/img/form8.png',
    audioSrc: '/_nuxt/public/audio/fruits/8_l.mp3',
    color: '#2de43f',
    index: 10,
    score: 5,
    point: 7,
  },
  {
    src: '/_nuxt/public/img/form3.png',
    audioSrc: '/_nuxt/public/audio/fruits/3_l.mp3',
    color: '#f038c4',
    index: 19,
    score: 30,
    point: 2,
  },
  {},
  {},
  {},
  {},
  {},
  {
    src: '/_nuxt/public/img/form7-2.png',
    audioSrc: '/_nuxt/public/audio/fruits/7_s.mp3',
    color: '#f038c4',
    index: 11,
    score: 10,
    point: 6,
  },
  {
    src: '/_nuxt/public/img/form6.png',
    audioSrc: '/_nuxt/public/audio/fruits/6_l.mp3',
    color: '#fd9a38',
    index: 18,
    score: 15,
    point: 5,
  },
  {
    src: '/_nuxt/public/img/form6-2.png',
    audioSrc: '/_nuxt/public/audio/fruits/6_s.mp3',
    color: '#f038c4',
    index: 17,
    score: 2,
    point: 5,
  },
  {
    src: '/_nuxt/public/img/form8.png',
    audioSrc: '/_nuxt/public/audio/fruits/8_l.mp3',
    color: '#2de43f',
    index: 16,
    score: 5,
    point: 7,
  },
  {
    src: '/_nuxt/public/img/form2.png',
    audioSrc: '/_nuxt/public/audio/fruits/2_l.mp3',
    color: '#fd9a38',
    index: 15,
    score: 40,
    point: 1,
  },
  {
    src: '/_nuxt/public/img/form2-2.png',
    audioSrc: '/_nuxt/public/audio/fruits/2_s.mp3',
    color: '#2de43f',
    index: 14,
    score: 2,
    point: 1,
  },
  {
    src: '/_nuxt/public/img/form5.png',
    audioSrc: '/_nuxt/public/audio/fruits/5_l.mp3',
    color: '#f038c4',
    index: 13,
    score: 20,
    point: 4,
  },
  {
    src: '/_nuxt/public/img/form7.png',
    audioSrc: '/_nuxt/public/audio/fruits/7_l.mp3',
    color: '#fd9a38',
    index: 12,
    score: 10,
    point: 6,
  },
]

export const sortedFruitsData = fruitsData
  .filter((item) => JSON.stringify(item) !== '{}')
  // @ts-ignore
  .sort((a, b) => a.index - b.index)
